repos:
  # --- Generic file formatters ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ["--autofix"]
      - id: requirements-txt-fixer

  # --- Markdown formatting ---
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.5.0
    hooks:
      - id: markdownlint

  # --- Shell script linting ---
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck

  # --- Dockerfile best practices ---
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

  # --- Java code formatting (via spotless) ---
  - repo: https://github.com/diffplug/spotless
    rev: 2.44.0
    hooks:
      - id: spotless-apply
        name: Java Spotless Format
        entry: mvn spotless:apply
        language: system
        types: [java]

  # --- Checkstyle (optional: for consistent Java style) ---
  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle Validation
        entry: mvn checkstyle:check
        language: system
        types: [java]

  # --- Ruby style (if you're using Watir/Cucumber automation) ---
  - repo: https://github.com/rubocop/rubocop
    rev: v1.64.0
    hooks:
      - id: rubocop
        name: Ruby Lint
        entry: bundle exec rubocop
        language: system
        types: [ruby]
        pass_filenames: false
